# Use Node LTS image
FROM node:20-alpine

# Set working directory inside the container - similar to "cd /app"
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy source code
COPY . .

# Expose the port your (backend)server runs on
EXPOSE 5000

# Command to start the server
CMD ["npm", "run", "start"]